/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-09-15 08:38:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Register;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("    <!DOCTYPE html>\n");
      out.write("    <html lang=\"en\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Track-Stock - Register</title>\n");
      out.write("     <link rel=\"icon\" type=\"image/x-icon\" href=\"../src/icon.png\">\n");
      out.write("        <!--Link for Icons-->\n");
      out.write("        <link\n");
      out.write("            href=\"https://cdn.jsdelivr.net/npm/remixicon@3.4.0/fonts/remixicon.css\"\n");
      out.write("            rel=\"stylesheet\"\n");
      out.write("        />\n");
      out.write("\n");
      out.write("        <!--Link for Cascading Style sheet(CSS)-->\n");
      out.write("        <link rel=\"stylesheet\" href=\"signup.css\">\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("    <!--login container Section-->\n");
      out.write("    <div class=\"login\" id=\"login\">\n");
      out.write("        <div>\n");
      out.write("            <a href=\"../Home/index.php\"> <img class=\"login__close\" src=\"../src/close.png\"></a>\n");
      out.write("        </div>\n");
      out.write("        <form action=\"../SignUpHandler\" class=\"login__form\" method=\"post\" onsubmit=\"return validInput()\">\n");
      out.write("            <h2 class=\"login__title\">Register Your Account</h2>\n");
      out.write("\n");
      out.write("            <div class=\"login__group\">\n");
      out.write("                <div>\n");
      out.write("                    <label for=\"username\" class=\"login__label\">Username</label>\n");
      out.write("                    <input\n");
      out.write("                        type=\"text\"\n");
      out.write("                        placeholder=\"Write your Username\"\n");
      out.write("                        id=\"username\"\n");
      out.write("                        name=\"username\"\n");
      out.write("                        class=\"login__input\"\n");
      out.write("                    />\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div>\n");
      out.write("                    <label for=\"email\" class=\"login__label\">Email</label>\n");
      out.write("                    <input\n");
      out.write("                        type=\"email\"\n");
      out.write("                        placeholder=\"Enter your Email\"\n");
      out.write("                        id=\"email\"\n");
      out.write("                        name=\"email\"\n");
      out.write("                        class=\"login__input\"\n");
      out.write("                    />\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div>\n");
      out.write("                    <label for=\"password\" class=\"login__label\">Password</label>\n");
      out.write("                    <input\n");
      out.write("                            style=\"margin-bottom: 30px;\"\n");
      out.write("                        type=\"password\"\n");
      out.write("                        placeholder=\"Enter your password\"\n");
      out.write("                        id=\"password\"\n");
      out.write("                        name=\"password\"\n");
      out.write("                        class=\"login__input\"\n");
      out.write("                    />\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <p class=\"login__signup\">Already Have An Account\n");
      out.write("                     <a href=\"../Login/Login.jsp\"> Sign In</a>\n");
      out.write("                </p>\n");
      out.write("                <input\n");
      out.write("                        id=\"checkbox\"\n");
      out.write("                        name=\"check\"\n");
      out.write("                        type=\"checkbox\"\n");
      out.write("                        class=\"login__forgot\"\n");
      out.write("                />\n");
      out.write("                I Agree to <a href=\"#\" >Terms and Conditions</a>\n");
      out.write("                   <p class=\"login__forgot\"><a href=\"#\">Privacy Policy</a></p>\n");
      out.write("\n");
      out.write("                <button type=\"submit\" class=\"login__button\" id=\"submit\">Sign Up</button>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("        <div id=\"alertmsg\">\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!--Background Image-->\n");
      out.write("    <main class=\"main\">\n");
      out.write("        <img src=\"../src/Background_login.JPG\" alt=\"image\" class=\"main__bg\"/>\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("    <!--script for handling errors-->\n");
      out.write("    <script>\n");
      out.write("\n");
      out.write("        window.onload = function() {\n");
      out.write("            checkcred();\n");
      out.write("            rearm();\n");
      out.write("\n");
      out.write("\n");
      out.write("            document.querySelector(\"form\").addEventListener(\"submit\", function(event) {\n");
      out.write("\n");
      out.write("                if (!validInput()) {\n");
      out.write("                    event.preventDefault();\n");
      out.write("                } else {\n");
      out.write("                    document.querySelector(\"#submit\").innerHTML = \"Signing In\";\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        function checkcred() {\n");
      out.write("            console.log(\"Checking credentials\");\n");
      out.write("            var signup_Fail = \"<?php echo $Signup_Fail ?>\";\n");
      out.write("            console.log(signup_Fail);\n");
      out.write("            var alertmsg = document.getElementById(\"alertmsg\");\n");
      out.write("            if (signup_Fail !== '') {\n");
      out.write("                alertmsg.style.display = \"block\";\n");
      out.write("                alertmsg.innerHTML = signup_Fail;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function rearm() {\n");
      out.write("            document.querySelector(\"#submit\").innerHTML = \"Sign Up\";\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function validInput() {\n");
      out.write("            var username = document.getElementById(\"username\").value;\n");
      out.write("            var password = document.getElementById(\"password\").value;\n");
      out.write("            var email = document.getElementById(\"email\").value;\n");
      out.write("            var alertmsg = document.getElementById(\"alertmsg\");\n");
      out.write("            var checked = document.getElementById(\"checkbox\");\n");
      out.write("\n");
      out.write("            if (username === '' || password === '' || email === '') {\n");
      out.write("                alertmsg.style.display = \"block\";\n");
      out.write("                alertmsg.innerHTML = \"Please Fill out All the Fields\";\n");
      out.write("                return false;\n");
      out.write("            } else {\n");
      out.write("                if(checked.checked){\n");
      out.write("                    alertmsg.style.display = \"none\";\n");
      out.write("                    return true;\n");
      out.write("                }\n");
      out.write("                else{\n");
      out.write("                    alertmsg.style.display = \"block\";\n");
      out.write("                    alertmsg.innerHTML = \"You must agree to terms and conditions\";\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("    </html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
